service: good-morning-info

plugins:
- serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: eu-west-1

custom:
  defaultStage: dev
  webpack: ./config/webpack/serverless.js
  webpackIncludeModules:
    packagePath: './package.json'
  environment:
    TABLE_CONFIGURATION: { "Ref": "configuration" }

functions:
  config-list:
    handler: lambda/configuration.list
    events:
      - http:
          path: config
          method: get

resources:
  Resources:
    configuration:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
